version: '3.8'

services:
  edk-sar-isce2:
    build:
      context: https://github.com/earth-data-kit/isce2.git
      dockerfile: docker/Dockerfile
      tags:
        - edk-sar-isce2:latest
    image: edk-sar-isce2:latest
    volumes:
      - ./..:/workspace  # Mount the entire codebase (assuming this compose file is in edk/edk-sar/edk_sar/)
      - ./../tmp:/tmp           # Mount the /tmp directory from host to container
      - ./../data:/data # Mount the data directory where user will put there SLCs and outputs will generated created
    working_dir: /workspace
    tty: true
